# shared/mongo_io.py
"""
MongoDB helper for all ASDT document storage.
Collections used:
  - assets               : static parcel metadata (soil type, texture, location)
  - diagnoses            : soil depletion diagnoses generated by agents
  - recommendations      : soil management recommendations
  - outcomes             : feedback on whether recommendations worked
  - escalations          : cases escalated to the Soil Scientist
  - state_transitions    : depletion state change log (S1–S8 ↔ healthy)
  - events               : system events (alerts, state changes, QA flags)
  - agent_interactions   : MAS coordination log
  - cross_domain_messages: messages sent/received from other DTs
"""
from pymongo import MongoClient
from datetime import datetime, timezone
from shared.config import MONGO_URI, MONGO_DB, ASSET_ID

_client = MongoClient(MONGO_URI)
_db     = _client[MONGO_DB]


# ── Static metadata ───────────────────────────────────────────────────────────

def upsert_asset_metadata(data: dict):
    """Insert or update the static soil parcel record in MongoDB."""
    _db.assets.update_one(
        {"asset_id": ASSET_ID},
        {"$set": {**data, "asset_id": ASSET_ID,
                  "updated_at": datetime.now(timezone.utc)}},
        upsert=True
    )

def get_asset_metadata() -> dict:
    return _db.assets.find_one({"asset_id": ASSET_ID}, {"_id": 0}) or {}


# ── Diagnoses ─────────────────────────────────────────────────────────────────

def save_diagnosis(diagnosis: dict) -> str:
    """Save a soil depletion diagnosis."""
    doc = {
        **diagnosis,
        "asset_id":   ASSET_ID,
        "created_at": datetime.now(timezone.utc),
    }
    result = _db.diagnoses.insert_one(doc)
    return str(result.inserted_id)

def get_diagnosis(diagnosis_id: str) -> dict:
    from bson import ObjectId
    doc = _db.diagnoses.find_one({"_id": ObjectId(diagnosis_id)}, {"_id": 0})
    return doc or {}


# ── Recommendations ───────────────────────────────────────────────────────────

def save_recommendation(rec: dict) -> str:
    """Save a soil management recommendation."""
    doc = {
        **rec,
        "asset_id":    ASSET_ID,
        "delivered_at": datetime.now(timezone.utc),
    }
    result = _db.recommendations.insert_one(doc)
    return str(result.inserted_id)


# ── Outcomes ──────────────────────────────────────────────────────────────────

def save_outcome(outcome: dict) -> str:
    """Record whether a recommendation worked."""
    doc = {
        **outcome,
        "asset_id":    ASSET_ID,
        "recorded_at": datetime.now(timezone.utc),
        "model_updated": False,
    }
    result = _db.outcomes.insert_one(doc)
    return str(result.inserted_id)


# ── Escalations ───────────────────────────────────────────────────────────────

def save_escalation(escalation: dict) -> str:
    """Save a case escalated to the Soil Scientist."""
    doc = {
        **escalation,
        "asset_id":  ASSET_ID,
        "escalated_at": datetime.now(timezone.utc),
        "learned": False,
    }
    result = _db.escalations.insert_one(doc)
    return str(result.inserted_id)


# ── State Transitions (S1–S8 ↔ Healthy) ──────────────────────────────────────

def save_state_transition(transition: dict) -> str:
    """Log a soil depletion state transition."""
    doc = {
        **transition,
        "asset_id":       ASSET_ID,
        "transitioned_at": datetime.now(timezone.utc),
    }
    result = _db.state_transitions.insert_one(doc)
    return str(result.inserted_id)

def get_recent_transitions(n: int = 20) -> list:
    return list(
        _db.state_transitions
        .find({"asset_id": ASSET_ID}, {"_id": 0})
        .sort("transitioned_at", -1)
        .limit(n)
    )


# ── Cross-Domain Messages ────────────────────────────────────────────────────

def save_cross_domain_message(message: dict) -> str:
    """Log a message sent to or received from another DT."""
    doc = {
        **message,
        "sent_at": datetime.now(timezone.utc),
    }
    result = _db.cross_domain_messages.insert_one(doc)
    return str(result.inserted_id)

def get_recent_cross_domain(n: int = 10) -> list:
    return list(
        _db.cross_domain_messages
        .find({}, {"_id": 0})
        .sort("sent_at", -1)
        .limit(n)
    )


# ── General event log ─────────────────────────────────────────────────────────

def log_event(event_type: str, payload: dict, severity: str = "info"):
    """Append a discrete event to the events collection."""
    _db.events.insert_one({
        "asset_id":   ASSET_ID,
        "event_type": event_type,
        "severity":   severity,
        "payload":    payload,
        "timestamp":  datetime.now(timezone.utc),
    })

def get_recent_events(n: int = 20) -> list:
    return list(
        _db.events
        .find({"asset_id": ASSET_ID}, {"_id": 0})
        .sort("timestamp", -1)
        .limit(n)
    )


# ── Agent interaction log ─────────────────────────────────────────────────────

def log_agent_interaction(workflow_id: str, calling_agent: str,
                          called_agent: str, request: dict, response: dict):
    """Log every inter-agent call for auditability."""
    _db.agent_interactions.insert_one({
        "workflow_id":    workflow_id,
        "calling_agent":  calling_agent,
        "called_agent":   called_agent,
        "request":        request,
        "response":       response,
        "timestamp":      datetime.now(timezone.utc),
    })


# ── Farmer reports (kept for backward compat, now optional) ──────────────────

def save_farmer_report(report: dict) -> str:
    doc = {
        **report,
        "asset_id":   ASSET_ID,
        "report_date": datetime.now(timezone.utc),
    }
    result = _db.farmer_reports.insert_one(doc)
    return str(result.inserted_id)